name = "Modified Cobblemon Plus"
version = "v11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "834f53f5c38f4c209be88cfad4347b84b47bcf5d70d7910cb7ede2fe8fc63f71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.144"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
