name = "Modified Cobblemon Plus"
version = "11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e423326b5b308f6b585897773df764cf63b2fc319ce951e71de87c07dc96b12d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
