name = "Modified Cobblemon Plus"
version = "11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aa32806ba145dd623bab47ba61666c0c1e6cd2d3749586675a26e7174d28c4b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.144"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
