name = "Modified Cobblemon Plus"
version = "11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b762ec28d7ce34434290db971485c9b333fdd07e496832a0bd577dc00b61559e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
