name = "Modified Cobblemon Plus"
version = "11.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e0f0ec4181232b229c3ca9c4271b8d126f930d410b2dad7b9b7338930046769"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.141"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
