name = "Modified Cobblemon Plus"
version = "v11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630160d43666ef1b5085d327bbaf84db056d6ce2d012c52a9b4aae6ec7183502"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.144"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
