name = "Modified Cobblemon Plus"
version = "v11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "098a4258449058fbda608c5e770dfd802ad73db8d6f52f12bf04a056b5003a4d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.144"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
