name = "Modified Cobblemon Plus"
version = "11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27745a236328683de5a335482d142fe5192691c6fff1cdc74c732311d245db41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.144"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
