name = "Modified Cobblemon Plus"
version = "11.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
<<<<<<< Updated upstream
hash = "95d4bbe04390bc3bcf2342cbef6cc60c8720e504c50f0d3770960090cf534e9b"
=======
hash = "d3cc00792e22c3d6d852e2c8150d4152e9c6742be57b2ede44b73950aabd5083"
>>>>>>> Stashed changes

[versions]
minecraft = "1.21.1"
neoforge = "21.1.141"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
