name = "Modified Cobblemon Plus"
version = "11.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "107c2f0db649e649dfb46104b34af3325febe405722ae3d2d06afe1806caecc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.145"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
