name = "Modified Cobblemon Plus"
version = "11.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721b30f754c339256ed974a95d0921aa56ef303f1f1f9085e4ea7af409352a40"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.141"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
